---
name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    if: github.event_name == 'pull_request'
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
